# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - run: rustup target add aarch64-apple-darwin

      - run: echo "pub fn api_key() -> &'static str { \"${{ secrets.FM_KEY }}\" }" >> src-tauri/src/main.rs
      - run: echo "pub fn api_secret() -> &'static str { \"${{ secrets.FM_SECRET }}\" }" >> src-tauri/src/main.rs

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'pnpm'

      - run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ 
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download and install this version of Mac Scrobble.\nMac.Scrobble___VERSION___x64.dmg\nMac.Scrobble___VERSION___aarch64.dmg'
          releaseDraft: true
          prerelease: false

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ 
          releaseName: "v__VERSION__"
          args: --target aarch64-apple-darwin
          releaseBody: 'See the assets to download and install this version of Mac Scrobble.\nMac.Scrobble___VERSION___x64.dmg\nMac.Scrobble___VERSION___aarch64.dmg'
          releaseDraft: true
          prerelease: false
